// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmhjtvqqocgkkbbzgwvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttaGp0dnFxb2Nna2tiYnpnd3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDU4NjAsImV4cCI6MjA2MjkyMTg2MH0.kfh8W3vVsNtyXq-rl7d_qQF8wNahXegbOSnUeXaQ0g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);